import { writeFile } from 'fs/promises'
import { readdir } from 'fs/promises'
import { join } from 'path'
import type { AddonBundle } from '../addons/types.js'

const HEADER = `# Project Rules

This file is auto-generated by \`@agencyq-007/cortex-core\`.
Regenerate with: \`npx @agencyq-007/cortex-core init --force\`

`

export async function writeClaudeMd(
  cwd: string,
  templatesDir: string,
  addons: AddonBundle[],
  dryRun: boolean,
): Promise<string> {
  const outPath = join(cwd, '.claude', 'CLAUDE.md')
  const imports: string[] = []

  // Core rules — scan templates to determine file list (works in both dry-run and normal mode)
  for (const dir of ['common', 'typescript']) {
    const templateDir = join(templatesDir, 'core', 'rules', dir)
    const files = (await readdir(templateDir)).filter((f) => f.endsWith('.md')).sort()
    for (const file of files) {
      imports.push(`@.claude/rules/${dir}/${file}`)
    }
  }

  // Addon rules
  for (const addon of addons) {
    if (!addon.rulesDir) continue
    const templateDir = join(templatesDir, 'addons', addon.rulesDir)
    const files = (await readdir(templateDir)).filter((f) => f.endsWith('.md')).sort()
    for (const file of files) {
      imports.push(`@.claude/rules/${addon.id}/${file}`)
    }
  }

  const content = HEADER + imports.join('\n') + '\n'

  if (!dryRun) {
    await writeFile(outPath, content, 'utf8')
  }

  return outPath
}
